#![forbid(unsafe_code)]

pub mod application;
pub mod background;
pub mod cli;
pub mod config;
pub mod constants;
pub mod contract;
pub mod core;
pub mod core_guardian;
pub mod core_service_ipc;
pub mod daemon;
mod digest;
pub mod domain;
pub mod error;
pub mod frontend_ipc;
pub mod ipc;
pub mod ipc_runtime;
pub mod lifecycle;
pub mod mihomo;
pub mod persistence;
pub mod process_controller;
pub mod production;
pub mod profile;
pub mod profile_source;
pub mod rule;
pub mod runtime_adapters;
pub mod runtime_bundle;
pub mod scheduler;
pub mod service;
pub mod shutdown_ipc;
pub mod state;
pub mod supervisor;
pub mod telemetry;
pub mod transaction;
pub mod tui;
pub mod tui_runtime;
mod unix_io;
pub mod validator;
